spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      routes:
        - id: fallback-users
          uri: lb://fallback-users
          predicates:
          - Path=/fallback/users/
        - id: users-microservice
          uri: lb://users-microservice
          predicates:
          - Path=/users/
          filters:
            - name: CircuitBreaker
              args:
                name: fetchUser
                fallbackUri: forward:/fallback/users/
  zipkin:
    base-url: http://zipkin:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    username: zipkin
    password: zipkin

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/