version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: zipkin
      RABBITMQ_DEFAULT_PASS: zipkin
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  mysql:
    image: mysql:5.6
    platform: linux/x86_64
    container_name: mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: zipkin
      MYSQL_PASSWORD: zipkin
      MYSQL_DATABASE: zipkin
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./mysql-import-db/import.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: unless-stopped
    ports:
      - '9411:9411'
    environment:
      RABBIT_ADDRESSES: rabbitmq
      RABBIT_USER: zipkin
      RABBIT_PASSWORD: zipkin
      STORAGE_TYPE: mysql
      MYSQL_USER: zipkin
      MYSQL_PASS: zipkin
      MYSQL_HOST: mysql
      MYSQL_TCP_PORT: 3306
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DESIGN: dracula
    depends_on:
      mysql:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    healthcheck:
      test: [ "CMD", "wget", "http://localhost:9090" ]
      interval: 30s
      timeout: 30s
      retries: 3

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_healthy