global:
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusText0.0.4
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []
scrape_configs:
  - job_name: users
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 10s
    scrape_timeout: 5s
    scrape_protocols:
      - OpenMetricsText1.0.0
      - OpenMetricsText0.0.1
      - PrometheusText0.0.4
    metrics_path: /actuator/prometheus
    scheme: http
    enable_compression: true
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - host.docker.internal:8081
  - job_name: fallback-users
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 10s
    scrape_timeout: 5s
    scrape_protocols:
      - OpenMetricsText1.0.0
      - OpenMetricsText0.0.1
      - PrometheusText0.0.4
    metrics_path: /actuator/prometheus
    scheme: http
    enable_compression: true
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - host.docker.internal:8082