spring:
  application:
    name: fallback-users
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config-server:8888
  zipkin:
    base-url: http://zipkin:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    username: zipkin
    password: zipkin

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
